require("dotenv").config();
const mongoose = require("mongoose");

const Category = require("./models/Category");
const Product = require("./models/Product");

async function connect() {
  if (!process.env.MONGO_URI) throw new Error("MONGO_URI missing");
  mongoose.set("strictQuery", true);
  await mongoose.connect(process.env.MONGO_URI);
  console.log("✅ Connected to MongoDB");
}

async function seed() {
  await connect();

  console.log("🧹 Clearing old data...");
  await Product.deleteMany({});
  await Category.deleteMany({});

  console.log("🌱 Creating categories...");
  const categories = await Category.insertMany([
    { name: "Men", slug: "men" },
    { name: "Women", slug: "women" },
    { name: "Kids", slug: "kids" },
    { name: "Footwear", slug: "footwear" },
    { name: "Accessories", slug: "accessories" },
  ]);

  const bySlug = Object.fromEntries(categories.map((c) => [c.slug, c._id]));

  console.log("🌱 Creating products...");
  await Product.insertMany([
    // MEN - 20 products
    {
      title: "Oversized Hoodie",
      brand: "StyloAI",
      description: "Heavyweight cotton hoodie with a relaxed fit.",
      price: 1299,
      originalPrice: 1999,
      discountPercent: 35,
      rating: 4.5,
      ratingCount: 312,
      categoryId: bySlug["men"],
      images: [
        "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["S", "M", "L", "XL"],
      inStock: true,
      stockQty: 50,
    },
    {
      title: "Slim Fit Denim Jeans",
      brand: "UrbanThread",
      description:
        "Classic blue denim with a modern slim fit and stretch comfort.",
      price: 1899,
      originalPrice: 2499,
      discountPercent: 24,
      rating: 4.3,
      ratingCount: 445,
      categoryId: bySlug["men"],
      images: [
        "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["30", "32", "34", "36", "38"],
      inStock: true,
      stockQty: 75,
    },
    {
      title: "Graphic Print T-Shirt",
      brand: "StreetWave",
      description: "Cotton tee with bold street-style graphic print.",
      price: 699,
      originalPrice: 999,
      discountPercent: 30,
      rating: 4.1,
      ratingCount: 203,
      categoryId: bySlug["men"],
      images: [
        "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["S", "M", "L", "XL", "XXL"],
      inStock: true,
      stockQty: 120,
    },
    {
      title: "Formal Dress Shirt",
      brand: "Executive",
      description:
        "Crisp white cotton dress shirt perfect for business settings.",
      price: 1499,
      originalPrice: 1999,
      discountPercent: 25,
      rating: 4.6,
      ratingCount: 178,
      categoryId: bySlug["men"],
      images: [
        "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["S", "M", "L", "XL"],
      inStock: true,
      stockQty: 45,
    },
    {
      title: "Bomber Jacket",
      brand: "StyloAI",
      description: "Classic bomber with ribbed cuffs and zippered pockets.",
      price: 2799,
      originalPrice: 3999,
      discountPercent: 30,
      rating: 4.7,
      ratingCount: 267,
      categoryId: bySlug["men"],
      images: [
        "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["M", "L", "XL"],
      inStock: true,
      stockQty: 35,
    },
    {
      title: "Cargo Pants",
      brand: "UrbanThread",
      description: "Utility cargo pants with multiple pockets and relaxed fit.",
      price: 1699,
      originalPrice: 2299,
      discountPercent: 26,
      rating: 4.4,
      ratingCount: 156,
      categoryId: bySlug["men"],
      images: [
        "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["30", "32", "34", "36"],
      inStock: true,
      stockQty: 60,
    },
    {
      title: "V-Neck Sweater",
      brand: "WoolCraft",
      description: "Soft merino wool blend sweater for layering.",
      price: 1999,
      originalPrice: 2799,
      discountPercent: 29,
      rating: 4.5,
      ratingCount: 189,
      categoryId: bySlug["men"],
      images: [
        "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["S", "M", "L", "XL"],
      inStock: true,
      stockQty: 40,
    },
    {
      title: "Track Pants",
      brand: "ActiveFit",
      description:
        "Comfortable joggers with elastic waistband and ankle cuffs.",
      price: 1199,
      originalPrice: 1699,
      discountPercent: 29,
      rating: 4.2,
      ratingCount: 298,
      categoryId: bySlug["men"],
      images: [
        "https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["S", "M", "L", "XL"],
      inStock: true,
      stockQty: 85,
    },
    {
      title: "Polo Shirt",
      brand: "StyloAI",
      description: "Classic polo with ribbed collar and short sleeves.",
      price: 899,
      originalPrice: 1299,
      discountPercent: 31,
      rating: 4.3,
      ratingCount: 221,
      categoryId: bySlug["men"],
      images: [
        "https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["S", "M", "L", "XL"],
      inStock: true,
      stockQty: 95,
    },
    {
      title: "Chino Shorts",
      brand: "SummerStyle",
      description: "Lightweight cotton chino shorts for warm weather.",
      price: 1099,
      originalPrice: 1599,
      discountPercent: 31,
      rating: 4.1,
      ratingCount: 167,
      categoryId: bySlug["men"],
      images: [
        "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["30", "32", "34", "36"],
      inStock: true,
      stockQty: 70,
    },
    {
      title: "Flannel Shirt",
      brand: "WoodlandWear",
      description: "Soft cotton flannel with classic plaid pattern.",
      price: 1399,
      originalPrice: 1899,
      discountPercent: 26,
      rating: 4.6,
      ratingCount: 234,
      categoryId: bySlug["men"],
      images: [
        "https://images.unsplash.com/photo-1598032895397-b9c644a45d8f?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["S", "M", "L", "XL"],
      inStock: true,
      stockQty: 55,
    },
    {
      title: "Leather Jacket",
      brand: "RoadKing",
      description: "Genuine leather biker jacket with asymmetric zipper.",
      price: 5999,
      originalPrice: 7999,
      discountPercent: 25,
      rating: 4.8,
      ratingCount: 142,
      categoryId: bySlug["men"],
      images: [
        "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["M", "L", "XL"],
      inStock: true,
      stockQty: 15,
    },
    {
      title: "Henley Long Sleeve",
      brand: "BasicEssentials",
      description: "Casual henley with buttoned placket and long sleeves.",
      price: 999,
      originalPrice: 1499,
      discountPercent: 33,
      rating: 4.4,
      ratingCount: 188,
      categoryId: bySlug["men"],
      images: [
        "https://images.unsplash.com/photo-1622445275463-afa2ab738c34?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["S", "M", "L", "XL"],
      inStock: true,
      stockQty: 80,
    },
    {
      title: "Windbreaker",
      brand: "StormGuard",
      description: "Lightweight water-resistant windbreaker with hood.",
      price: 1799,
      originalPrice: 2499,
      discountPercent: 28,
      rating: 4.3,
      ratingCount: 176,
      categoryId: bySlug["men"],
      images: [
        "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["M", "L", "XL", "XXL"],
      inStock: true,
      stockQty: 45,
    },
    {
      title: "Swim Shorts",
      brand: "BeachVibes",
      description: "Quick-dry swim shorts with mesh lining and drawstring.",
      price: 899,
      originalPrice: 1299,
      discountPercent: 31,
      rating: 4.0,
      ratingCount: 145,
      categoryId: bySlug["men"],
      images: [
        "https://images.unsplash.com/photo-1560298803-1d998f6b5249?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["S", "M", "L", "XL"],
      inStock: true,
      stockQty: 65,
    },
    {
      title: "Turtleneck Sweater",
      brand: "WoolCraft",
      description: "Cozy turtleneck in soft knit fabric.",
      price: 2199,
      originalPrice: 2999,
      discountPercent: 27,
      rating: 4.5,
      ratingCount: 134,
      categoryId: bySlug["men"],
      images: [
        "https://images.unsplash.com/photo-1578587018452-892bacefd3f2?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["S", "M", "L", "XL"],
      inStock: true,
      stockQty: 35,
    },
    {
      title: "Denim Jacket",
      brand: "UrbanThread",
      description: "Classic blue denim jacket with button closure.",
      price: 2299,
      originalPrice: 2999,
      discountPercent: 23,
      rating: 4.6,
      ratingCount: 289,
      categoryId: bySlug["men"],
      images: [
        "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["S", "M", "L", "XL"],
      inStock: true,
      stockQty: 50,
    },
    {
      title: "Performance Tank Top",
      brand: "ActiveFit",
      description: "Moisture-wicking tank top for workouts.",
      price: 699,
      originalPrice: 999,
      discountPercent: 30,
      rating: 4.2,
      ratingCount: 212,
      categoryId: bySlug["men"],
      images: [
        "https://images.unsplash.com/photo-1622124925019-93e832f29ea0?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["S", "M", "L", "XL"],
      inStock: true,
      stockQty: 100,
    },
    {
      title: "Quilted Vest",
      brand: "OutdoorGear",
      description: "Insulated quilted vest for layering in cool weather.",
      price: 1899,
      originalPrice: 2599,
      discountPercent: 27,
      rating: 4.4,
      ratingCount: 156,
      categoryId: bySlug["men"],
      images: [
        "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["M", "L", "XL"],
      inStock: true,
      stockQty: 40,
    },
    {
      title: "Linen Shirt",
      brand: "SummerStyle",
      description: "Breathable linen shirt perfect for summer days.",
      price: 1599,
      originalPrice: 2199,
      discountPercent: 27,
      rating: 4.3,
      ratingCount: 198,
      categoryId: bySlug["men"],
      images: [
        "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["S", "M", "L", "XL"],
      inStock: true,
      stockQty: 55,
    },

    // WOMEN - 20 products
    {
      title: "Women's Blazer",
      brand: "StyloAI",
      description: "Smart blazer for office and casual layering.",
      price: 2999,
      originalPrice: 3999,
      discountPercent: 25,
      rating: 4.6,
      ratingCount: 190,
      categoryId: bySlug["women"],
      images: [
        "https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["S", "M", "L"],
      inStock: true,
      stockQty: 20,
    },
    {
      title: "Floral Maxi Dress",
      brand: "FloraFashion",
      description: "Elegant flowing maxi dress with beautiful floral print.",
      price: 2199,
      originalPrice: 2999,
      discountPercent: 27,
      rating: 4.7,
      ratingCount: 334,
      categoryId: bySlug["women"],
      images: [
        "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["XS", "S", "M", "L", "XL"],
      inStock: true,
      stockQty: 45,
    },
    {
      title: "High-Waisted Jeans",
      brand: "DenimLux",
      description: "Flattering high-rise skinny jeans with stretch.",
      price: 1999,
      originalPrice: 2699,
      discountPercent: 26,
      rating: 4.5,
      ratingCount: 512,
      categoryId: bySlug["women"],
      images: [
        "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["24", "26", "28", "30", "32"],
      inStock: true,
      stockQty: 80,
    },
    {
      title: "Cashmere Sweater",
      brand: "LuxeKnit",
      description: "Premium cashmere pullover with crew neck.",
      price: 3999,
      originalPrice: 5999,
      discountPercent: 33,
      rating: 4.8,
      ratingCount: 167,
      categoryId: bySlug["women"],
      images: [
        "https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["XS", "S", "M", "L"],
      inStock: true,
      stockQty: 25,
    },
    {
      title: "Silk Blouse",
      brand: "ElegantWear",
      description: "Luxurious silk blouse with button front closure.",
      price: 2499,
      originalPrice: 3499,
      discountPercent: 29,
      rating: 4.6,
      ratingCount: 223,
      categoryId: bySlug["women"],
      images: [
        "https://images.unsplash.com/photo-1618932260643-eee4a2f652a6?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["XS", "S", "M", "L"],
      inStock: true,
      stockQty: 35,
    },
    {
      title: "Pleated Midi Skirt",
      brand: "ChicStyle",
      description: "Elegant pleated skirt with elastic waistband.",
      price: 1599,
      originalPrice: 2199,
      discountPercent: 27,
      rating: 4.4,
      ratingCount: 189,
      categoryId: bySlug["women"],
      images: [
        "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["XS", "S", "M", "L"],
      inStock: true,
      stockQty: 50,
    },
    {
      title: "Trench Coat",
      brand: "ClassicOuterwear",
      description: "Timeless double-breasted trench with belt.",
      price: 3499,
      originalPrice: 4999,
      discountPercent: 30,
      rating: 4.7,
      ratingCount: 145,
      categoryId: bySlug["women"],
      images: [
        "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["S", "M", "L"],
      inStock: true,
      stockQty: 20,
    },
    {
      title: "Yoga Leggings",
      brand: "FitFlex",
      description: "High-performance leggings with pocket and compression fit.",
      price: 1299,
      originalPrice: 1799,
      discountPercent: 28,
      rating: 4.6,
      ratingCount: 678,
      categoryId: bySlug["women"],
      images: [
        "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["XS", "S", "M", "L", "XL"],
      inStock: true,
      stockQty: 150,
    },
    {
      title: "Wrap Dress",
      brand: "FloraFashion",
      description: "Flattering wrap dress with adjustable tie waist.",
      price: 1899,
      originalPrice: 2599,
      discountPercent: 27,
      rating: 4.5,
      ratingCount: 267,
      categoryId: bySlug["women"],
      images: [
        "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["XS", "S", "M", "L"],
      inStock: true,
      stockQty: 40,
    },
    {
      title: "Cardigan Sweater",
      brand: "CozyKnits",
      description: "Soft open-front cardigan for easy layering.",
      price: 1799,
      originalPrice: 2399,
      discountPercent: 25,
      rating: 4.4,
      ratingCount: 312,
      categoryId: bySlug["women"],
      images: [
        "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["S", "M", "L", "XL"],
      inStock: true,
      stockQty: 60,
    },
    {
      title: "Wide Leg Pants",
      brand: "ModernFit",
      description: "Flowy wide-leg trousers with high waist.",
      price: 1999,
      originalPrice: 2799,
      discountPercent: 29,
      rating: 4.3,
      ratingCount: 198,
      categoryId: bySlug["women"],
      images: [
        "https://images.unsplash.com/photo-1594633313593-bab3825d0caf?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["XS", "S", "M", "L"],
      inStock: true,
      stockQty: 45,
    },
    {
      title: "Camisole Top",
      brand: "BasicEssentials",
      description: "Silky camisole with adjustable straps.",
      price: 799,
      originalPrice: 1199,
      discountPercent: 33,
      rating: 4.2,
      ratingCount: 445,
      categoryId: bySlug["women"],
      images: [
        "https://images.unsplash.com/photo-1564584217132-2271feaeb3c5?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["XS", "S", "M", "L"],
      inStock: true,
      stockQty: 90,
    },
    {
      title: "Women's Denim Jacket",
      brand: "DenimLux",
      description: "Classic cropped denim jacket with distressed details.",
      price: 2299,
      originalPrice: 2999,
      discountPercent: 23,
      rating: 4.6,
      ratingCount: 356,
      categoryId: bySlug["women"],
      images: [
        "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["XS", "S", "M", "L"],
      inStock: true,
      stockQty: 55,
    },
    {
      title: "Lace Bodysuit",
      brand: "Intimates",
      description: "Delicate lace bodysuit with snap closure.",
      price: 1499,
      originalPrice: 1999,
      discountPercent: 25,
      rating: 4.3,
      ratingCount: 234,
      categoryId: bySlug["women"],
      images: [
        "https://images.unsplash.com/photo-1578342976795-062a1b744f37?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["XS", "S", "M", "L"],
      inStock: true,
      stockQty: 30,
    },
    {
      title: "Pencil Skirt",
      brand: "WorkWear",
      description: "Professional knee-length pencil skirt.",
      price: 1399,
      originalPrice: 1899,
      discountPercent: 26,
      rating: 4.4,
      ratingCount: 167,
      categoryId: bySlug["women"],
      images: [
        "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["XS", "S", "M", "L"],
      inStock: true,
      stockQty: 50,
    },
    {
      title: "Puffer Jacket",
      brand: "WinterWarmth",
      description: "Warm quilted puffer with faux fur hood trim.",
      price: 3299,
      originalPrice: 4499,
      discountPercent: 27,
      rating: 4.7,
      ratingCount: 289,
      categoryId: bySlug["women"],
      images: [
        "https://images.unsplash.com/photo-1544923246-77f609b0f905?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["S", "M", "L", "XL"],
      inStock: true,
      stockQty: 35,
    },
    {
      title: "Jumpsuit",
      brand: "ChicStyle",
      description: "One-piece jumpsuit with waist tie and pockets.",
      price: 2399,
      originalPrice: 3199,
      discountPercent: 25,
      rating: 4.5,
      ratingCount: 178,
      categoryId: bySlug["women"],
      images: [
        "https://images.unsplash.com/photo-1585487000143-3b0b79fe7a2f?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["XS", "S", "M", "L"],
      inStock: true,
      stockQty: 40,
    },
    {
      title: "Turtleneck Top",
      brand: "CozyKnits",
      description: "Fitted ribbed turtleneck in soft fabric.",
      price: 999,
      originalPrice: 1499,
      discountPercent: 33,
      rating: 4.3,
      ratingCount: 298,
      categoryId: bySlug["women"],
      images: [
        "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["XS", "S", "M", "L"],
      inStock: true,
      stockQty: 70,
    },
    {
      title: "Summer Romper",
      brand: "BeachVibes",
      description: "Lightweight romper with floral print and tie waist.",
      price: 1399,
      originalPrice: 1899,
      discountPercent: 26,
      rating: 4.2,
      ratingCount: 213,
      categoryId: bySlug["women"],
      images: [
        "https://images.unsplash.com/photo-1566206091558-7f218b696731?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["XS", "S", "M", "L"],
      inStock: true,
      stockQty: 55,
    },
    {
      title: "Knit Sweater Dress",
      brand: "LuxeKnit",
      description: "Cozy sweater dress with turtleneck and long sleeves.",
      price: 2799,
      originalPrice: 3799,
      discountPercent: 26,
      rating: 4.6,
      ratingCount: 189,
      categoryId: bySlug["women"],
      images: [
        "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["S", "M", "L"],
      inStock: true,
      stockQty: 30,
    },

    // KIDS - 20 products
    {
      title: "Kids Graphic Tee",
      brand: "FunKids",
      description: "Colorful cotton t-shirt with playful graphic print.",
      price: 599,
      originalPrice: 899,
      discountPercent: 33,
      rating: 4.3,
      ratingCount: 456,
      categoryId: bySlug["kids"],
      images: [
        "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
      inStock: true,
      stockQty: 120,
    },
    {
      title: "Kids Denim Overalls",
      brand: "PlayTime",
      description: "Adjustable denim overalls with front pocket.",
      price: 1299,
      originalPrice: 1799,
      discountPercent: 28,
      rating: 4.5,
      ratingCount: 234,
      categoryId: bySlug["kids"],
      images: [
        "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
      inStock: true,
      stockQty: 60,
    },
    {
      title: "Kids Hoodie",
      brand: "FunKids",
      description: "Cozy pullover hoodie with kangaroo pocket.",
      price: 899,
      originalPrice: 1299,
      discountPercent: 31,
      rating: 4.4,
      ratingCount: 345,
      categoryId: bySlug["kids"],
      images: [
        "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-11Y"],
      inStock: true,
      stockQty: 85,
    },
    {
      title: "Kids Joggers",
      brand: "ActiveKids",
      description: "Comfortable jogger pants with elastic waist.",
      price: 799,
      originalPrice: 1099,
      discountPercent: 27,
      rating: 4.3,
      ratingCount: 278,
      categoryId: bySlug["kids"],
      images: [
        "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
      inStock: true,
      stockQty: 100,
    },
    {
      title: "Kids Puffer Jacket",
      brand: "WarmKids",
      description: "Lightweight puffer jacket for chilly days.",
      price: 1599,
      originalPrice: 2199,
      discountPercent: 27,
      rating: 4.6,
      ratingCount: 189,
      categoryId: bySlug["kids"],
      images: [
        "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
      inStock: true,
      stockQty: 50,
    },
    {
      title: "Kids Dress",
      brand: "PrettyGirls",
      description: "Floral print dress with ruffled hem.",
      price: 1099,
      originalPrice: 1499,
      discountPercent: 27,
      rating: 4.5,
      ratingCount: 312,
      categoryId: bySlug["kids"],
      images: [
        "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
      inStock: true,
      stockQty: 70,
    },
    {
      title: "Kids Shorts",
      brand: "PlayTime",
      description: "Cotton shorts with elastic waistband.",
      price: 499,
      originalPrice: 699,
      discountPercent: 29,
      rating: 4.2,
      ratingCount: 234,
      categoryId: bySlug["kids"],
      images: [
        "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
      inStock: true,
      stockQty: 150,
    },
    {
      title: "Kids Polo Shirt",
      brand: "SmartKids",
      description: "Classic polo shirt for school or casual wear.",
      price: 699,
      originalPrice: 999,
      discountPercent: 30,
      rating: 4.4,
      ratingCount: 198,
      categoryId: bySlug["kids"],
      images: [
        "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["4-5Y", "6-7Y", "8-9Y", "10-11Y"],
      inStock: true,
      stockQty: 90,
    },
    {
      title: "Kids Cardigan",
      brand: "CozyKids",
      description: "Button-front cardigan in soft knit.",
      price: 899,
      originalPrice: 1299,
      discountPercent: 31,
      rating: 4.3,
      ratingCount: 167,
      categoryId: bySlug["kids"],
      images: [
        "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
      inStock: true,
      stockQty: 65,
    },
    {
      title: "Kids Jeans",
      brand: "DenimKids",
      description: "Comfortable stretch jeans with adjustable waist.",
      price: 999,
      originalPrice: 1399,
      discountPercent: 29,
      rating: 4.5,
      ratingCount: 289,
      categoryId: bySlug["kids"],
      images: [
        "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-11Y"],
      inStock: true,
      stockQty: 80,
    },
    {
      title: "Kids Raincoat",
      brand: "RainyDays",
      description: "Waterproof raincoat with hood.",
      price: 1299,
      originalPrice: 1799,
      discountPercent: 28,
      rating: 4.6,
      ratingCount: 156,
      categoryId: bySlug["kids"],
      images: [
        "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
      inStock: true,
      stockQty: 45,
    },
    {
      title: "Kids Leggings",
      brand: "ActiveKids",
      description: "Stretchy leggings with fun patterns.",
      price: 599,
      originalPrice: 899,
      discountPercent: 33,
      rating: 4.3,
      ratingCount: 312,
      categoryId: bySlug["kids"],
      images: [
        "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
      inStock: true,
      stockQty: 110,
    },
    {
      title: "Kids Sweater",
      brand: "CozyKids",
      description: "Warm knit sweater with crew neck.",
      price: 999,
      originalPrice: 1399,
      discountPercent: 29,
      rating: 4.4,
      ratingCount: 198,
      categoryId: bySlug["kids"],
      images: [
        "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
      inStock: true,
      stockQty: 70,
    },
    {
      title: "Kids Skirt",
      brand: "PrettyGirls",
      description: "Pleated skirt with elastic waistband.",
      price: 699,
      originalPrice: 999,
      discountPercent: 30,
      rating: 4.2,
      ratingCount: 145,
      categoryId: bySlug["kids"],
      images: [
        "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
      inStock: true,
      stockQty: 55,
    },
    {
      title: "Kids Tracksuit",
      brand: "ActiveKids",
      description: "Matching hoodie and pants set.",
      price: 1499,
      originalPrice: 1999,
      discountPercent: 25,
      rating: 4.5,
      ratingCount: 234,
      categoryId: bySlug["kids"],
      images: [
        "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
      inStock: true,
      stockQty: 60,
    },
    {
      title: "Kids Denim Jacket",
      brand: "DenimKids",
      description: "Classic denim jacket with button closure.",
      price: 1299,
      originalPrice: 1799,
      discountPercent: 28,
      rating: 4.6,
      ratingCount: 178,
      categoryId: bySlug["kids"],
      images: [
        "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["4-5Y", "6-7Y", "8-9Y", "10-11Y"],
      inStock: true,
      stockQty: 50,
    },
    {
      title: "Kids Pajama Set",
      brand: "SleepyTime",
      description: "Soft cotton pajama set with fun prints.",
      price: 799,
      originalPrice: 1099,
      discountPercent: 27,
      rating: 4.7,
      ratingCount: 389,
      categoryId: bySlug["kids"],
      images: [
        "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
      inStock: true,
      stockQty: 95,
    },
    {
      title: "Kids Swim Trunks",
      brand: "SplashKids",
      description: "Quick-dry swim trunks with fun prints.",
      price: 599,
      originalPrice: 899,
      discountPercent: 33,
      rating: 4.3,
      ratingCount: 212,
      categoryId: bySlug["kids"],
      images: [
        "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
      inStock: true,
      stockQty: 75,
    },
    {
      title: "Kids Formal Shirt",
      brand: "SmartKids",
      description: "Button-down dress shirt for special occasions.",
      price: 899,
      originalPrice: 1299,
      discountPercent: 31,
      rating: 4.4,
      ratingCount: 145,
      categoryId: bySlug["kids"],
      images: [
        "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["4-5Y", "6-7Y", "8-9Y", "10-11Y"],
      inStock: true,
      stockQty: 40,
    },
    {
      title: "Kids Fleece Pants",
      brand: "WarmKids",
      description: "Cozy fleece-lined pants for cold weather.",
      price: 899,
      originalPrice: 1299,
      discountPercent: 31,
      rating: 4.5,
      ratingCount: 189,
      categoryId: bySlug["kids"],
      images: [
        "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
      inStock: true,
      stockQty: 65,
    },

    // FOOTWEAR - 20 products
    {
      title: "Minimal Sneakers",
      brand: "StyloAI",
      description: "Clean everyday sneakers. Comfortable and durable.",
      price: 2499,
      originalPrice: 3499,
      discountPercent: 29,
      rating: 4.2,
      ratingCount: 221,
      categoryId: bySlug["footwear"],
      images: [
        "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["7", "8", "9", "10", "11"],
      inStock: true,
      stockQty: 30,
    },
    {
      title: "Running Shoes",
      brand: "SpeedFit",
      description: "Lightweight running shoes with cushioned sole.",
      price: 3299,
      originalPrice: 4499,
      discountPercent: 27,
      rating: 4.7,
      ratingCount: 567,
      categoryId: bySlug["footwear"],
      images: [
        "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["7", "8", "9", "10", "11", "12"],
      inStock: true,
      stockQty: 80,
    },
    {
      title: "Leather Boots",
      brand: "BootCraft",
      description: "Premium leather ankle boots with side zipper.",
      price: 4499,
      originalPrice: 5999,
      discountPercent: 25,
      rating: 4.8,
      ratingCount: 234,
      categoryId: bySlug["footwear"],
      images: [
        "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["6", "7", "8", "9", "10"],
      inStock: true,
      stockQty: 35,
    },
    {
      title: "Canvas Slip-Ons",
      brand: "CasualStep",
      description: "Easy slip-on canvas shoes for everyday wear.",
      price: 1499,
      originalPrice: 1999,
      discountPercent: 25,
      rating: 4.3,
      ratingCount: 389,
      categoryId: bySlug["footwear"],
      images: [
        "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["7", "8", "9", "10", "11"],
      inStock: true,
      stockQty: 100,
    },
    {
      title: "High Heels",
      brand: "ElegantSteps",
      description: "Classic pointed-toe pumps with stiletto heel.",
      price: 2999,
      originalPrice: 3999,
      discountPercent: 25,
      rating: 4.4,
      ratingCount: 178,
      categoryId: bySlug["footwear"],
      images: [
        "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["5", "6", "7", "8", "9"],
      inStock: true,
      stockQty: 45,
    },
    {
      title: "Hiking Boots",
      brand: "TrailMaster",
      description: "Waterproof hiking boots with ankle support.",
      price: 4999,
      originalPrice: 6499,
      discountPercent: 23,
      rating: 4.7,
      ratingCount: 312,
      categoryId: bySlug["footwear"],
      images: [
        "https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["7", "8", "9", "10", "11", "12"],
      inStock: true,
      stockQty: 50,
    },
    {
      title: "Flip Flops",
      brand: "BeachWalk",
      description: "Comfortable rubber flip flops for beach and pool.",
      price: 499,
      originalPrice: 799,
      discountPercent: 38,
      rating: 4.0,
      ratingCount: 456,
      categoryId: bySlug["footwear"],
      images: [
        "https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["7", "8", "9", "10", "11"],
      inStock: true,
      stockQty: 200,
    },
    {
      title: "Ballet Flats",
      brand: "GracefulSteps",
      description: "Elegant ballet flats with bow detail.",
      price: 1799,
      originalPrice: 2399,
      discountPercent: 25,
      rating: 4.5,
      ratingCount: 267,
      categoryId: bySlug["footwear"],
      images: [
        "https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["5", "6", "7", "8", "9"],
      inStock: true,
      stockQty: 65,
    },
    {
      title: "Basketball Shoes",
      brand: "HoopStar",
      description: "High-top basketball shoes with excellent grip.",
      price: 3999,
      originalPrice: 5499,
      discountPercent: 27,
      rating: 4.6,
      ratingCount: 423,
      categoryId: bySlug["footwear"],
      images: [
        "https://images.unsplash.com/photo-1579338559194-a162d19bf842?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["8", "9", "10", "11", "12"],
      inStock: true,
      stockQty: 55,
    },
    {
      title: "Loafers",
      brand: "ClassicWear",
      description: "Leather penny loafers for smart casual style.",
      price: 2799,
      originalPrice: 3699,
      discountPercent: 24,
      rating: 4.5,
      ratingCount: 189,
      categoryId: bySlug["footwear"],
      images: [
        "https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["7", "8", "9", "10", "11"],
      inStock: true,
      stockQty: 40,
    },
    {
      title: "Sandals",
      brand: "SummerStride",
      description: "Strappy leather sandals with adjustable buckles.",
      price: 1599,
      originalPrice: 2199,
      discountPercent: 27,
      rating: 4.3,
      ratingCount: 234,
      categoryId: bySlug["footwear"],
      images: [
        "https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["5", "6", "7", "8", "9"],
      inStock: true,
      stockQty: 70,
    },
    {
      title: "Chelsea Boots",
      brand: "BootCraft",
      description: "Suede Chelsea boots with elastic side panels.",
      price: 3999,
      originalPrice: 5299,
      discountPercent: 25,
      rating: 4.7,
      ratingCount: 198,
      categoryId: bySlug["footwear"],
      images: [
        "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["7", "8", "9", "10", "11"],
      inStock: true,
      stockQty: 30,
    },
    {
      title: "Cross Trainers",
      brand: "GymPro",
      description: "Versatile training shoes for gym workouts.",
      price: 2899,
      originalPrice: 3899,
      discountPercent: 26,
      rating: 4.4,
      ratingCount: 345,
      categoryId: bySlug["footwear"],
      images: [
        "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["7", "8", "9", "10", "11", "12"],
      inStock: true,
      stockQty: 75,
    },
    {
      title: "Wedge Heels",
      brand: "ElegantSteps",
      description: "Comfortable wedge sandals with platform sole.",
      price: 2499,
      originalPrice: 3299,
      discountPercent: 24,
      rating: 4.5,
      ratingCount: 212,
      categoryId: bySlug["footwear"],
      images: [
        "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["5", "6", "7", "8", "9"],
      inStock: true,
      stockQty: 50,
    },
    {
      title: "Boat Shoes",
      brand: "NauticalWear",
      description: "Classic leather boat shoes with non-slip sole.",
      price: 2299,
      originalPrice: 2999,
      discountPercent: 23,
      rating: 4.3,
      ratingCount: 167,
      categoryId: bySlug["footwear"],
      images: [
        "https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["7", "8", "9", "10", "11"],
      inStock: true,
      stockQty: 45,
    },
    {
      title: "Winter Snow Boots",
      brand: "ArcticWear",
      description: "Insulated waterproof boots for cold weather.",
      price: 4499,
      originalPrice: 5999,
      discountPercent: 25,
      rating: 4.8,
      ratingCount: 278,
      categoryId: bySlug["footwear"],
      images: [
        "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["6", "7", "8", "9", "10", "11"],
      inStock: true,
      stockQty: 40,
    },
    {
      title: "Espadrilles",
      brand: "SummerStride",
      description: "Canvas espadrilles with jute rope sole.",
      price: 1299,
      originalPrice: 1799,
      discountPercent: 28,
      rating: 4.2,
      ratingCount: 189,
      categoryId: bySlug["footwear"],
      images: [
        "https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["5", "6", "7", "8", "9"],
      inStock: true,
      stockQty: 60,
    },
    {
      title: "Kids Sneakers",
      brand: "TinySteps",
      description: "Colorful sneakers with velcro straps for easy wear.",
      price: 1299,
      originalPrice: 1799,
      discountPercent: 28,
      rating: 4.6,
      ratingCount: 456,
      categoryId: bySlug["footwear"],
      images: [
        "https://images.unsplash.com/photo-1514989940723-e8e51635b782?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["10", "11", "12", "13", "1", "2"],
      inStock: true,
      stockQty: 90,
    },
    {
      title: "Oxford Dress Shoes",
      brand: "FormalWear",
      description: "Polished leather Oxford shoes for formal occasions.",
      price: 3499,
      originalPrice: 4699,
      discountPercent: 26,
      rating: 4.6,
      ratingCount: 145,
      categoryId: bySlug["footwear"],
      images: [
        "https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["7", "8", "9", "10", "11"],
      inStock: true,
      stockQty: 35,
    },
    {
      title: "Skateboard Shoes",
      brand: "SkateLife",
      description: "Durable skate shoes with reinforced toe cap.",
      price: 2199,
      originalPrice: 2999,
      discountPercent: 27,
      rating: 4.4,
      ratingCount: 298,
      categoryId: bySlug["footwear"],
      images: [
        "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: ["7", "8", "9", "10", "11"],
      inStock: true,
      stockQty: 65,
    },

    // ACCESSORIES - 20 products
    {
      title: "Leather Belt",
      brand: "StyloAI",
      description: "Premium belt with a classic buckle.",
      price: 799,
      originalPrice: 999,
      discountPercent: 20,
      rating: 4.1,
      ratingCount: 88,
      categoryId: bySlug["accessories"],
      images: [
        "https://images.unsplash.com/photo-1624222247344-550fb60583bb?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: [],
      inStock: true,
      stockQty: 100,
    },
    {
      title: "Sunglasses",
      brand: "ShadeStyle",
      description: "UV protection sunglasses with polarized lenses.",
      price: 1499,
      originalPrice: 1999,
      discountPercent: 25,
      rating: 4.5,
      ratingCount: 423,
      categoryId: bySlug["accessories"],
      images: [
        "https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: [],
      inStock: true,
      stockQty: 150,
    },
    {
      title: "Leather Wallet",
      brand: "WalletCraft",
      description: "Genuine leather bifold wallet with card slots.",
      price: 1299,
      originalPrice: 1799,
      discountPercent: 28,
      rating: 4.6,
      ratingCount: 567,
      categoryId: bySlug["accessories"],
      images: [
        "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: [],
      inStock: true,
      stockQty: 120,
    },
    {
      title: "Baseball Cap",
      brand: "CapKing",
      description: "Adjustable cotton baseball cap with embroidered logo.",
      price: 699,
      originalPrice: 999,
      discountPercent: 30,
      rating: 4.3,
      ratingCount: 312,
      categoryId: bySlug["accessories"],
      images: [
        "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: [],
      inStock: true,
      stockQty: 200,
    },
    {
      title: "Backpack",
      brand: "PackPro",
      description: "Durable laptop backpack with multiple compartments.",
      price: 2499,
      originalPrice: 3299,
      discountPercent: 24,
      rating: 4.7,
      ratingCount: 489,
      categoryId: bySlug["accessories"],
      images: [
        "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: [],
      inStock: true,
      stockQty: 80,
    },
    {
      title: "Watch",
      brand: "TimeMaster",
      description: "Classic analog watch with leather strap.",
      price: 2999,
      originalPrice: 3999,
      discountPercent: 25,
      rating: 4.6,
      ratingCount: 356,
      categoryId: bySlug["accessories"],
      images: [
        "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: [],
      inStock: true,
      stockQty: 45,
    },
    {
      title: "Scarf",
      brand: "WarmWrap",
      description: "Soft wool blend scarf for cold weather.",
      price: 899,
      originalPrice: 1299,
      discountPercent: 31,
      rating: 4.4,
      ratingCount: 234,
      categoryId: bySlug["accessories"],
      images: [
        "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: [],
      inStock: true,
      stockQty: 90,
    },
    {
      title: "Beanie",
      brand: "WarmHead",
      description: "Knitted beanie with fold-over cuff.",
      price: 599,
      originalPrice: 899,
      discountPercent: 33,
      rating: 4.3,
      ratingCount: 278,
      categoryId: bySlug["accessories"],
      images: [
        "https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: [],
      inStock: true,
      stockQty: 120,
    },
    {
      title: "Crossbody Bag",
      brand: "BagStyle",
      description: "Compact crossbody bag with adjustable strap.",
      price: 1799,
      originalPrice: 2399,
      discountPercent: 25,
      rating: 4.5,
      ratingCount: 312,
      categoryId: bySlug["accessories"],
      images: [
        "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: [],
      inStock: true,
      stockQty: 65,
    },
    {
      title: "Leather Gloves",
      brand: "WarmHands",
      description: "Premium leather gloves with soft lining.",
      price: 1299,
      originalPrice: 1799,
      discountPercent: 28,
      rating: 4.4,
      ratingCount: 189,
      categoryId: bySlug["accessories"],
      images: [
        "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: [],
      inStock: true,
      stockQty: 55,
    },
    {
      title: "Tote Bag",
      brand: "BagStyle",
      description: "Spacious canvas tote bag for everyday use.",
      price: 1499,
      originalPrice: 1999,
      discountPercent: 25,
      rating: 4.3,
      ratingCount: 267,
      categoryId: bySlug["accessories"],
      images: [
        "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: [],
      inStock: true,
      stockQty: 75,
    },
    {
      title: "Tie",
      brand: "FormalStyle",
      description: "Silk tie with classic pattern.",
      price: 799,
      originalPrice: 1199,
      discountPercent: 33,
      rating: 4.2,
      ratingCount: 145,
      categoryId: bySlug["accessories"],
      images: [
        "https://images.unsplash.com/photo-1624222247344-550fb60583bb?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: [],
      inStock: true,
      stockQty: 100,
    },
    {
      title: "Bracelet",
      brand: "JewelCraft",
      description: "Stylish leather and metal bracelet.",
      price: 599,
      originalPrice: 899,
      discountPercent: 33,
      rating: 4.1,
      ratingCount: 198,
      categoryId: bySlug["accessories"],
      images: [
        "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: [],
      inStock: true,
      stockQty: 150,
    },
    {
      title: "Duffle Bag",
      brand: "TravelGear",
      description: "Spacious duffle bag for weekend trips.",
      price: 2299,
      originalPrice: 2999,
      discountPercent: 23,
      rating: 4.6,
      ratingCount: 234,
      categoryId: bySlug["accessories"],
      images: [
        "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: [],
      inStock: true,
      stockQty: 40,
    },
    {
      title: "Hair Accessories Set",
      brand: "StyleUp",
      description: "Set of clips, bands, and pins.",
      price: 399,
      originalPrice: 599,
      discountPercent: 33,
      rating: 4.2,
      ratingCount: 345,
      categoryId: bySlug["accessories"],
      images: [
        "https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: [],
      inStock: true,
      stockQty: 200,
    },
    {
      title: "Umbrella",
      brand: "RainGuard",
      description: "Compact folding umbrella with auto-open.",
      price: 699,
      originalPrice: 999,
      discountPercent: 30,
      rating: 4.3,
      ratingCount: 267,
      categoryId: bySlug["accessories"],
      images: [
        "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: [],
      inStock: true,
      stockQty: 85,
    },
    {
      title: "Phone Case",
      brand: "TechStyle",
      description: "Protective phone case with stylish design.",
      price: 499,
      originalPrice: 799,
      discountPercent: 38,
      rating: 4.1,
      ratingCount: 456,
      categoryId: bySlug["accessories"],
      images: [
        "https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: [],
      inStock: true,
      stockQty: 250,
    },
    {
      title: "Keychain",
      brand: "AccessoryPlus",
      description: "Leather keychain with metal clasp.",
      price: 299,
      originalPrice: 499,
      discountPercent: 40,
      rating: 4.0,
      ratingCount: 178,
      categoryId: bySlug["accessories"],
      images: [
        "https://images.unsplash.com/photo-1624222247344-550fb60583bb?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: [],
      inStock: true,
      stockQty: 300,
    },
    {
      title: "Earrings Set",
      brand: "JewelCraft",
      description: "Set of elegant stud earrings.",
      price: 899,
      originalPrice: 1299,
      discountPercent: 31,
      rating: 4.4,
      ratingCount: 234,
      categoryId: bySlug["accessories"],
      images: [
        "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: [],
      inStock: true,
      stockQty: 120,
    },
    {
      title: "Necklace",
      brand: "JewelCraft",
      description: "Delicate chain necklace with pendant.",
      price: 1299,
      originalPrice: 1799,
      discountPercent: 28,
      rating: 4.5,
      ratingCount: 289,
      categoryId: bySlug["accessories"],
      images: [
        "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=900&q=80",
      ],
      sizes: [],
      inStock: true,
      stockQty: 80,
    },
  ]);

  console.log("✅ Seed complete.");
  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
